<a href="https://colab.research.google.com/github/Bragmotik/laboratory/blob/main/%D0%AF%D0%BA%D0%BE%D0%B2%D0%BB%D0%B5%D0%B2%D0%B0_%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_%E2%84%961.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.2. Посчитайте размер матрицы Z в байтах и выведите его на печать. Чтобы узнать
размер (в байтах) 1 элемента матрицы используйте
атрибут https://docs.scipy.org/doc/numpy1.15.1/reference/generated/numpy.ndarray.itemsize.html
Примечание. В этой задаче не нужно ничего считывать - матрица Z уже заполнена.
Sample Input 1:
np.zeros((10,10))
Sample Output 1:
800
Sample Input 2:
np.array([1,2,3], dtype=np.float64)
Sample Output 2:
24

In [1]:
import timeit
import numpy as np
 
def python(byte):
    Z = byte
    len(Z)*8
 
def mat(byte):
    Z = np.array(byte)
    Z.itemsize*Z.size
 
if __name__ == '__main__':
    start_time = timeit.default_timer();
    python([1, 3, 6, 7, 8])
    range_time_1 = timeit.default_timer()- start_time
  
    start_time = timeit.default_timer();
    mat([1, 3, 6, 7, 8])
    arange_time_1 = timeit.default_timer()- start_time
 
    start_time = timeit.default_timer();
    python(np.zeros((10,10)))
    range_time_2 = timeit.default_timer()- start_time
  
    start_time = timeit.default_timer();
    mat(np.zeros((10, 10)))
    arange_time_2 = timeit.default_timer()- start_time

In [3]:
print('Array [1, 3, 6, 7, 8]')
print(f'size of array [1, 3, 6, 7, 8]: range() время {range_time_1}')
print(f'size of array [1, 3, 6, 7, 8] arange() время {arange_time_1}')
 
print('Array 10×10')
print(f'size of array 10×10: range() время {range_time_2}')
print(f'size of array 10×10: arange() время {arange_time_2}')


Array [1, 3, 6, 7, 8]
size of array [1, 3, 6, 7, 8]: range() время 1.484999756939942e-06
size of array [1, 3, 6, 7, 8] arange() время 0.0001226960002895794
Array 10×10
size of array 10×10: range() время 4.2950000079144957e-05
size of array 10×10: arange() время 4.405800018503214e-05


In [5]:
Z=np.zeros((10,10))
Z.itemsize*Z.size

800

In [7]:
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
Z=np.array([1,2,3], dtype=np.float64)
Z.itemsize*Z.size

24

In [9]:
print(Z)


[1. 2. 3.]


In [15]:
type(Z)
Z=str(np.array(Z))
type(Z)


str